# fly.toml file generated for ctf-cannaregio on 2023-01-19T10:38:42-05:00

app = "ctf-cannaregio"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  POSTGRES_PASSWORD = "2jxPW6aoSLXdkejrJCUi0lohF7b94akQ"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5432
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["pg_tls"]
    port = 5432

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"
