# fly.toml file generated for ctf-jwt on 2022-12-26T13:31:59-05:00

app = "ctf-jwt"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PHX_HOST = "ctf-jwt.fly.dev"
  PORT = "8080"
  SECRET_KEY_BASE = "a3VTsFNTX6uu8SesDlPceK3p06qo/E5CB6QHinqkLuuhMjd0LsLZYA0XG03KNZMP"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "15s"
    method = "get"
    path = "/ping"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
